export const GenomeEnvironmentList: string[] = [
  'acid hot spring',
  'acid mine drainage',
  'activated sludge',
  'algal bloom',
  'alkaline hot spring',
  'anaerobic digester',
  'antarctic',
  'aquarium',
  'aquifer',
  'arctic',
  'beach sand',
  'biochar',
  'biofilm',
  'biofilter',
  'biomass associated',
  'bioreactor',
  'bog',
  'bone',
  'cave',
  'cecum',
  'cerebrospinal fluid',
  'clay',
  'cloth',
  'coal',
  'coalbed',
  'cold seep',
  'compost',
  'coral reef',
  'corrosion',
  'cryosol',
  'deep',
  'dental plaque',
  'desert',
  'drain water',
  'drinking water',
  'estuary',
  'feces',
  'fen',
  'fish associated',
  'food associated',
  'freshwater',
  'freshwater sediment',
  'geothermal',
  'glacier',
  'ground water',
  'groundwater sediment',
  'gut',
  'hindgut',
  'hot spring',
  'human activity associated',
  'hydrothermal sediment',
  'hydrothermal vent',
  'hypersaline lake',
  'hypersaline pond',
  'hypolimnion',
  'ice',
  'insecta associated',
  'inside',
  'lake',
  'lake sediment',
  'lake water',
  'landfill',
  'leaf',
  'lower urinary tract',
  'lung',
  'mangrove',
  'marine sediment',
  'marine water',
  'meadow soil',
  'midgut',
  'mucosa',
  'mud',
  'mud volcano',
  'nasopharyngeal',
  'oil associated feature',
  'oral cavity',
  'paddy field soil',
  'peat',
  'permafrost',
  'petroleum',
  'plant body associated',
  'plastic debris',
  'polar',
  'pond',
  'respiratory tract',
  'rhizosphere',
  'rice paddy soil',
  'river',
  'river sediment',
  'rock',
  'root nodule',
  'rumen',
  'saline lake',
  'saline lake sediment',
  'saliva',
  'salt',
  'salt lake',
  'salt marsh',
  'savanna soil',
  'sea',
  'sediment',
  'sewage',
  'skin',
  'sludge',
  'snow',
  'soda lake',
  'soil',
  'sponge',
  'stromatolite mat',
  'subgingival plaque',
  'subsurface',
  'subterrestrial',
  'supragingival plaque',
  'symbiotic microbe',
  'terrestrial',
  'travertine',
  'tundra',
  'vagina',
  'volcano associated feature',
  'waste water',
  'water',
  'wetland',
  'wetland soil',
  'wood',
  'woodland',
]
